# This configuration file is for the **development** setup.
# For a production example please refer to getredash/setup repository on GitHub.
version: "2.2"
x-redash-service: &redash-service
  build:
    context: .
    args:
      skip_frontend_build: "false"
  env_file: ./redash_conf/env
  volumes:
    - .:/app
services:
  server:
    <<: *redash-service
    # command: server
    # command: dev_server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
      - "5678:5678"
  scheduler:
    <<: *redash-service
    command: scheduler
    depends_on:
      - server
  worker:
    <<: *redash-service
    command: worker
    depends_on:
      - server
  redis:
    image: redis:3-alpine
    restart: unless-stopped
  postgres:
    image: postgres:9.6-alpine
    env_file: ./redash_conf/env
    volumes:
      - /Users/wellytambunan/Repos/bea-cukai-labs/redash/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  email:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
    restart: unless-stopped